### ISSUE TITLE
TypeError when trying to generate comments

### ISSUE THREAD

**Issue by warpdesign** [smartcomments/smartcomments#31]
I'm getting this error when trying to generate comments:

``` sh
smartcomments --generate
Hello!!!
using smartcomments@0.3.0 on node@0.10.24
-Looking Config ...
-Using default config...
-Looking Files ...
...We found 36 files...
-Generating comments...

/usr/local/share/npm/lib/node_modules/smartcomments/lib/smartcomments.js:232
            return (matchValRe.exec(srcValue)[1] === matchValRe.exec(genValue)
                                             ^
TypeError: Cannot read property '1' of null
    at Object.SmartComments.isSameParam (/usr/local/share/npm/lib/node_modules/smartcomments/lib/smartcomments.js:232:46)
    at /usr/local/share/npm/lib/node_modules/smartcomments/lib/smartcomments.js:180:66
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/share/npm/lib/node_modules/smartcomments/node_modules/underscore/underscore.js:79:11)
    at /usr/local/share/npm/lib/node_modules/smartcomments/lib/smartcomments.js:179:23
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/share/npm/lib/node_modules/smartcomments/node_modules/underscore/underscore.js:79:11)
    at Object.SmartComments.mergeSrcAndGeneratedComment (/usr/local/share/npm/lib/node_modules/smartcomments/lib/smartcomments.js:173:15)
    at /usr/local/share/npm/lib/node_modules/smartcomments/lib/smartcomments.js:127:30
    at Array.forEach (native)
```

**Comment by darielnoel** [comment]
Hi, thanks for the feedback. The error was fixed in the 0.3.2 version. Would you like to try again, Please?

Best Regards, Dariel
