### ISSUE TITLE
Another TypeError when trying generating comments

### ISSUE THREAD

**Issue by unfalse** [smartcomments/smartcomments#34]
```
D:\temp\smartComments>smartcomments -g
Hello!!!
using smartcomments@0.3.2 on node@0.10.32
-Looking Config ...
-Using default config...
-Looking Files ...
...We found 136 files...
-Generating comments...

C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:345
                switch (node.type) {
                            ^
TypeError: Cannot read property 'type' of null
    at Object.Walker_walkElement [as walkElement] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:345:29)
    at Object.Walker_walkExpressionArray [as walkExpressionArray] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:211:38)
    at Object.Walker_walkElement [as walkElement] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:365:34)
    at Object.Walker_walkElement [as walkElement] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:840:38)
    at Object.Walker_walkVariableArray [as walkVariableArray] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:281:34)
    at Object.Walker_walkElement [as walkElement] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:825:34)
    at Object.Walker_walkStatementArray [as walkStatementArray] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:187:34)
    at Object.Walker_walkElement [as walkElement] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:661:34)
    at Object.Walker_walk [as walk] (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\node_modules\eswalker\walker.js:885:29)
    at Object.SmartComments.generate (C:\Users\User1\AppData\Roaming\npm\node_modules\smartcomments\lib\smartcomments.js:99:46)
```

**Comment by jmurowaniecki** [comment]
Humm.. Perhaps this message `using smartcomments@0.3.2 on node@0.10.32` means that it's time :watch: to update your nodejs, dude (:

**Comment by davidportella** [comment]
This problem is also in node 10.37, probably in all 10.x

```
Hello!!!
using smartcomments@0.3.2 on node@0.10.37
-Looking Config ... 
-Using default config...
-Looking Files ...
...We found 6838 files...
-Generating comments... 

/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:345
                switch (node.type) {
                            ^
TypeError: Cannot read property 'type' of null
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:345:29)
    at Object.Walker_walkExpressionArray [as walkExpressionArray] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:211:38)
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:365:34)
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:605:34)
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:617:34)
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:690:38)
    at Object.Walker_walkStatementArray [as walkStatementArray] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:187:34)
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:379:34)
    at Object.Walker_walkElement [as walkElement] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:535:38)
    at Object.Walker_walkStatementArray [as walkStatementArray] (/usr/lib/node_modules/smartcomments/node_modules/eswalker/walker.js:187:34)
```
